name: blorbmart2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  webview_flutter: ^4.11.0
  shared_preferences: ^2.5.3
  universal_html: ^2.2.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  fluttertoast: ^8.2.12
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0
  shimmer: ^3.0.0
  location: ^8.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_launcher_icons: ^0.14.3
  connectivity_plus: ^6.1.4
  photo_view: ^0.15.0
  google_sign_in: ^6.3.0
  toastification: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Fonts section (only one instance)
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700