// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKG09EfN4LrAqYaJ6WTphBN4BEl3DYwbQ',
    appId: '1:323656404685:web:e3aab9d81a57e7f0b0e384',
    messagingSenderId: '323656404685',
    projectId: 'blorbmart2',
    authDomain: 'blorbmart2.firebaseapp.com',
    storageBucket: 'blorbmart2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtD0NcnbTWNSz8zPTupx3c-8DEdgMmo3w',
    appId: '1:323656404685:android:d3896b80b073e0a0b0e384',
    messagingSenderId: '323656404685',
    projectId: 'blorbmart2',
    storageBucket: 'blorbmart2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEPkAVVpu7JMnNVApA8c39dE9iSF54NjU',
    appId: '1:323656404685:ios:1a22a8a9a5a3fb0db0e384',
    messagingSenderId: '323656404685',
    projectId: 'blorbmart2',
    storageBucket: 'blorbmart2.firebasestorage.app',
    iosBundleId: 'com.example.blorbmart2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEPkAVVpu7JMnNVApA8c39dE9iSF54NjU',
    appId: '1:323656404685:ios:1a22a8a9a5a3fb0db0e384',
    messagingSenderId: '323656404685',
    projectId: 'blorbmart2',
    storageBucket: 'blorbmart2.firebasestorage.app',
    iosBundleId: 'com.example.blorbmart2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKG09EfN4LrAqYaJ6WTphBN4BEl3DYwbQ',
    appId: '1:323656404685:web:87eebe40e638ae5ab0e384',
    messagingSenderId: '323656404685',
    projectId: 'blorbmart2',
    authDomain: 'blorbmart2.firebaseapp.com',
    storageBucket: 'blorbmart2.firebasestorage.app',
  );
}
